### ISSUE TITLE
probably forgotten debug output

### ISSUE THREAD

**Issue by mmaulwurff** [tunbridgep/doom-simpleteleportereffects#1]
https://github.com/tunbridgep/doom-simpleteleportereffects/blob/32e98d743ecf78fb962dd071afe1b1c99b5b887b/src/zsc/teleporter_effects.zsc#L164

Messages like
```Health value: 1
Health value: 1
Health value: 1
Health value: 1
Health value: 1
Health value: 1
```
may confuse users.

**Comment by tunbridgep** [comment]
Right. Will fix this. Sorry I don't know why I completely missed this bug report. It was supposed to go to my email and didn't.

Will be fixed for next release.
